### ISSUE TITLE
Issues with portrait tablet

### ISSUE THREAD

**Issue by doamatto** [mello-app/static-website#11]
![image](https://user-images.githubusercontent.com/30969346/104505337-951c9380-5598-11eb-93c1-31d730bea20b.png)

**Comment by cyckl** [comment]
This fix does break spacing on desktop though:
![image](https://user-images.githubusercontent.com/26363850/122608271-c1997780-d030-11eb-8d6f-f042d6a88e67.png)

```scss
    @media (min-width: 900px) {
        flex-direction: row;
        > div, > img {
            // These two margin assignments conflict with each other on desktop
            margin: 1em 2em;
            @media (min-width: 900px) { margin: 1em auto; }
            max-width: 600pt;
        }
        > img { height: 40vh; }
    }
```

I've gone ahead and removed the problematic media query line in a commit.

![image](https://user-images.githubusercontent.com/26363850/122608526-3a003880-d031-11eb-8611-07c6e2fb3c1c.png)
